# Generated by Django 5.0.6 on 2024-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, verbose_name='дата создания')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('slug', models.CharField(blank='True', max_length=150, null='True', verbose_name='URL')),
                ('content', models.TextField(blank='True', null='True', verbose_name='содержимое')),
                ('preview', models.ImageField(blank='True', null='True', upload_to='media/photo')),
                ('published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('views', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение продукта', null=True, upload_to='media/photo', verbose_name='Изображение(превью)'),
        ),
    ]
