# Generated by Django 4.2.2 on 2024-07-11 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_edit', 'может редактировать блог')], 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'title'], 'permissions': [('can_canceled_public', 'может отменять публикацию продукта'), ('can_edit_desk', 'может менять описание продукта'), ('can_edit_category', 'может менять категорию продукта')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(blank='True', help_text='Укажите владельца продукта', null='True', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=False, verbose_name='опубликован'),
        ),
    ]
